### ISSUE TITLE
Package is not Download From Github Link in Unity

### ISSUE THREAD

**Issue by Meet-BVM** [appodeal/appodeal-unity-plugin-upm#50] opened 2024-03-12 08:56 UTC
## Step 0: Is this a new bug?
Make sure to check our
[troubleshooting](https://docs.appodeal.com/faq-and-troubleshooting/troubleshooting/unity-common-issues/65k-reference-limit)
and [issues](https://github.com/appodeal/appodeal-unity-plugin-upm/issues) pages before submitting your bug report.

*Please delete this section when posting a bug report.*

## Step 1: Environment

**[REQUIRED]**
 - Computer OS: [e.g. Windows, macOS]
 - Unity Editor Version: [e.g. 2021.3.1f1]
 - Appodeal Unity Plugin Version: [e.g. 3.0.1]
 - Bug Repro Rate: [e.g. 100%, 25%]

**[OPTIONAL]** *(if applicable)*
 - Xcode Version: [e.g. 13.3.1]
 - CocoaPods Version: [e.g. 1.11.3]
 - Device Model: [e.g. Pixel 6 Pro, iPhone 13]
 - Device OS Version: [e.g. Android 13, iOS 15.4.1]

## Step 2: Describe the bug
A clear and concise description of what the bug is, including device logs, Unity Editor logs, and stack traces if available.

## Step 3: How to reproduce
Describe here step by step how to reproduce this bug.
[e.g. 1. Initialize SDK. 2. Call `Appodeal.Show(AppodealAdType.Mrec);`. 3. See error.]

## Step 6: Additional context

*If you have a downloadable sample project that reproduces the bug you're reporting, you will likely receive a faster response on your issue.*

**Comment by Meet-BVM** [comment] 2024-03-12 11:46
Hi Team

I want Use Your Plugin In unity But I follow Step in your documation copy
link and paste in Unity Package Manager (Install Package From Git URl) not
Working

**Comment by Meet-BVM** [comment] 2024-03-12 12:02
And Also After i Build Game Then Show Me Gradle Error Also Please Guide Me
To Solve it

Thank You

**Comment by Meet-BVM** [comment] 2024-03-12 12:39
And One More Thing I Already Integration in unity But Also Show me Error
Please Check

**Comment by Khrolovich** [comment] 2024-03-12 17:07
We cannot see attachments in GitHub. Please, try to check [troubleshooting](https://docs.appodeal.com/faq-and-troubleshooting/troubleshooting/unity-common-issues/billing-library-collision) pages and provide detailed information according to our template if you still haven't found a solution.

We need detailed information regarding steps to reproduce the issue and the used environment.

**Comment by Meet-BVM** [comment] 2024-03-13 05:22
Dear Appodeal Team,

I hope this email finds you well. I am writing to confirm our scheduled
AnyDesk session for integrating Appodeal into my Unity project.

Session Date: 13 - 3 - 2024
Session Time: 2:00 PM Indian Standard Time (IST)

I am looking forward to our session and am eager to learn the necessary
steps to seamlessly integrate Appodeal into my Unity project. Please let me
know if there are any preparations I should make beforehand to ensure a
smooth session.

Additionally, if there are any specific materials or resources you
recommend reviewing prior to our session, please do not hesitate to share
them with me.

Thank you very much for your assistance, and I appreciate your time and
expertise in guiding me through this integration process.

Best regards,
Meet

**Comment by Khrolovich** [comment] 2024-03-13 11:13
Hello @Meet-BVM,

We do not offer integration sessions. I have to close this issue because you didn't provide the requested information.

Don't hesitate to check our [documentation](https://docs.appodeal.com/) and ask the support team (support@appodeal.com) for help.

If you found an issue in the SDK, please follow our template during the issue creation.

**Closed by Khrolovich** 2024-03-13 11:13 UTC
Labels: bug
